services:
  telegraf:
    image: telegraf:1.33.0
    #image: telegraf-custom:latest
    container_name: telegraf
    volumes:
      - ${OTEL_POC_DIR}/configs/gpu/nvidia-smi/case_default/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  

    restart: always
  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=testdb
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_USER=telegraf
      - INFLUXDB_USER_PASSWORD=telegraf123
    volumes:
      - ${OTEL_POC_VOLUMES}/gpu/nvidia-smi/case_default/influxdb:/var/lib/influxdb
      - ${OTEL_POC_DIR}/configs/gpu/nvidia-smi/case_default/influxdb:/etc/influxdb
    restart: always

  chronograf:
    image: chronograf:1.5.0
    container_name: chronograf
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - influxdb
    restart: always

